services:
  - type: web
    name: poetry-generator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.10
      - key: FLASK_ENV
        value: production